converter/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('converter.views',
    # Examples:
    url(r'^structured', 'structured'),
    url(r'^semi-structured', 'semi_structured'),
    url(r'^un-structured', 'un_structured'),
)

tripleConverter/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()
from django.conf import settings

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'converter.views.home'),
    url(r'^converter/', include('converter.urls')),
    url(r'^json/', include('converter.urls_json')),
    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT} ),
)

converter/models.py
from django.db import models
from django.core.files.storage import FileSystemStorage
from django.conf import settings
import os

class OverwriteStorage(FileSystemStorage):
    def get_available_name(self, name):
        """
            make the slug file name available to the folder to write the code content
        """
        # If the filename already exists, remove it as if it was a true file system
        file_path = os.path.join(settings.MEDIA_ROOT, name)
        if self.exists(file_path):
            os.remove(file_path)
        return file_path

class Database( models.Model ):
    """
        list of supported database in the application
    """
    name = models.CharField( max_length = 50 )
    version = models.PositiveSmallIntegerField()
    slug = models.CharField( max_length = 55, unique = True )
    description = models.TextField( null = True , blank = True, default = "what does it supports...?")
    code_file = models.FileField( upload_to = 'converter/hooks', null = True, blank = True, storage = OverwriteStorage())
    code = models.TextField( null = True , blank = True)
    location = models.CharField( max_length = 15 , help_text = "IP of the database system")
    db_name = models.CharField( max_length = 50 , help_text = "Default database to connect")
    username = models.CharField( max_length = 50 )
    password = models.CharField( max_length = 50 )
    active = models.BooleanField( default = True )
    created_on = models.DateField( auto_now_add = True )
    
    class Meta:
        unique_together = ( 'name', 'version' )
    
    def __unicode__( self ):
        return "%s - %s" %( self.name, self.version )

    def save(self, *args, **kwargs):
        if self.code_file:
            self.code = self.code_file.read()
        super(Database, self).save(*args, **kwargs)

converter/forms.py
from django import forms
from converter.utils import get_source_list

class StructuredDataForm( forms.Form ):
    source = forms.TypedChoiceField()
    database = forms.TypedChoiceField(required = False)
    table = forms.TypedChoiceField(required = False)
    query = forms.CharField(widget=forms.Textarea, required = False)
    response = forms.CharField(widget=forms.Textarea, required = False)

    def __init__(self, *args, **kwargs):
        super(StructuredDataForm, self).__init__(*args, **kwargs)
        choices = [('','Please select Source')]
        choices.extend(get_source_list())
        self.fields['source'].choices = choices

converter/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from converter.models import Database
from converter.utils import get_source_list, get_database_list, get_table_list,\
         get_data, transform_to_triple
from converter.ajax_methods import get_choice_data

@staff_member_required
def home(request):
    group_list = request.user.groups.all().values_list('name', flat = True)
    data = {'group_list' : group_list}
    return render_to_response('index.html', data, context_instance=RequestContext(request))

@staff_member_required
def structured(request):
    group_list = request.user.groups.all().values_list('name', flat = True)
    source_list = get_choice_data('Source', get_source_list())
    if request.POST:
        try:
            source = request.POST.get('source')
            db_name = request.POST.get('database')
            table_name = request.POST.get('table')
            query = request.POST.get('query')
            response = []
            if db_name:
                db_list = get_choice_data('DB', get_database_list(source))
                if table_name:
                    table_list = get_choice_data('Table', get_table_list(source, db_name))
                    query = "select * from %s limit 10;" %(table_name)
                    response = get_data(source, db_name, query)
                    triple_response = transform_to_triple(source, db_name, table_name, response)
        except Exception as e:
            response = "There is some error with the program for selected input please check\n\n%s" %(e)
        source = str(source)
    return render_to_response('converter/structured.html', locals(), context_instance=RequestContext(request))
 
@staff_member_required
def semi_structured(request):
    data = {}
    return render_to_response('not_available.html', data, context_instance=RequestContext(request))

@staff_member_required
def un_structured(request):
    data = {}
    return render_to_response('not_available.html', data, context_instance=RequestContext(request))

templates/ajax_select_box.html
{% for key,value in data %}
    <option value="{{key}}">{{value}}</option>
{% endfor %}

templates/base.html
{% extends "admin/base.html" %}
{% load i18n %}

{% block title %}{{ title }} | {% trans 'Triple Converter' %}{% endblock %}

{% block branding %}
    <h1 id="site-name" style="text-align:center;">{% trans 'Triple Converter' %}</h1>
{% endblock %}

{% block breadcrumbs %}
    <div class = breadcrumbs>
        <a href="/" title="Home">Home</a>
    </div>
{% endblock %}

{% block nav-global %}{% endblock %}

templates/converter/structured.html
{% extends "base.html" %}

{% load i18n admin_modify adminmedia %}
{% block extrahead %}{{ block.super }}
    {% url admin:jsi18n as jsi18nurl %}
    <script type="text/javascript" src="/admin/jsi18n/"></script>
    <script type="text/javascript" src="{{ MEDIA_URL }}scripts/jquery-1.5.1.min.js"></script>
    <script type="text/javascript">
        function validate(){
            a = $('#id_source').val();
            b = $('#id_database').val();
            c = $('#id_table').val();
            if (a == ""|a == null|b == ""|b == null|c == ""|c == null){
                alert('Please fill all the parameters before submit');
                return false;
            }
            else{
                return true;
            }
        }
        function change_database(a){
            $.get('/json/get_database_list/', {'source':a},function(data){$('#id_database').html(data)});
        }
        function change_tablelist(a,b){
            $.get('/json/get_table_list/', {'source':a, 'database': b},function(data){$('#id_table').html(data)});
        }
        $(document).ready(function(){
                $("#id_source").change(function () {
                    var str = "";
                    $("#id_source option:selected").each(function () {
                        str = this.value;
                        });
                    change_database(str);
                    })

                $("#id_database").change(function () {
                    var str = "";
                    $("#id_database option:selected").each(function () {
                        str = this.value;
                        });
                    change_tablelist($("#id_source").val(), str );
                    })
            })
   </script>
{% endblock %}
{% block content %}
    <div id="content-main">
        {% if "Admin" in group_list %}
            <div class="module">
                <table>
                    <caption><a href="#" class="section" title="Admin">Administration</a></caption>
                    <tr><th scope="row"><a href="/admin/converter/database/" title="Manage Database">{% blocktrans %}Manage Datasource{% endblocktrans %}</a></th></tr>
                </table>
            </div>
        {% endif %}
    </div>
    <h3>You can select data source here</h3>
    <form action="" method="post" onsubmit="return validate();">
        {% csrf_token %}
        <select name="source" id="id_source">
            {% for item in source_list %}
                <option value="{{item.0}}"{% ifequal item.0 source %} selected="selected"{% endifequal %}>{{item.1}}</option>
            {% endfor %}
        </select>

        <select name="database" id="id_database">
            {% for item in db_list %}
                <option value="{{item.0}}"{% ifequal item.0 db_name %} selected="selected"{% endifequal %}>{{item.1}}</option>
            {% endfor %}
        </select>
        
        <select name="table" id="id_table">
            {% for item in table_list %}
                <option value="{{item.0}}"{% ifequal item.0 table_name %} selected="selected"{% endifequal %}>{{item.1}}</option>
            {% endfor %}
        </select>
        <input type="submit" value="Submit" />
        <hr/>
        <h4>Showing top 10 data for the selected table:</h4>
        <textarea name="response" id="id_response" rows=10 cols=80>{{response}}</textarea>
        <hr/>
        <h4>Showing triple model for the above data:</h4>
        {{triple_response|safe}}
    </form>
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load i18n %}
{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% load adminmedia %}{% admin_media_prefix %}css/dashboard.css" />{% endblock %}
{% block coltype %}colMS{% endblock %}
{% block bodyclass %}dashboard{% endblock %}

{% block content %}
    <h1>Triple Conversion System</h1>
    <div id="content-main">
        <div class="module">
            <table>
                <caption><a href="#" class="section" title="Converter">{% blocktrans %}Structured{% endblocktrans %}</a></caption>
                <tr><th scope="row"><a href="/converter/structured" title="Converet Tripple">Use It Now</a></th></tr>
            </table>
        </div>

        <div class="module">
            <table>
                <caption><a href="#" class="section" title="Converter">{% blocktrans %}Semi-Structured{% endblocktrans %}</a></caption>
                <tr><th scope="row"><a href="/converter/semi-structured" title="Converet Tripple">Use It Now</a></th></tr>
            </table>
        </div>

        <div class="module">
            <table>
                <caption><a href="#" class="section" title="Converter">{% blocktrans %}Un-Structured{% endblocktrans %}</a></caption>
                <tr><th scope="row"><a href="/converter/un-structured" title="Converet Tripple">Use It Now</a></th></tr>
            </table>
        </div>
</div>
{% endblock %}

{% block sidebar %}
    <div id="content-related"></div>
{% endblock %}

templates/not_available.html
{% extends "base.html" %}
{% block content %}
    <h1 style="padding-left:200px;padding-top:100px;">Uploaded soon...</h1>
{% endblock %}